In [2]:
def loadDataSet():
    postingList = [['my','dog','has','flea','problems','help','please'],
                   ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                   ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                   ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                   ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                   ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0,1,0,1,0,1]
    return postingList, classVec

In [8]:
def createVocabList(dataSet) : 
    vocabSet = set([])
    for document in dataSet : 
        vocabSet = vocabSet | set(document)
        print(set(document))
    print(vocabSet)
    return list(vocabSet)

In [6]:
postingList, classVec = loadDataSet()

In [10]:
myvocablist=createVocabList(postingList)
myvocablist.index("love")
myvocablist

{'please', 'has', 'help', 'problems', 'flea', 'my', 'dog'}
{'not', 'to', 'him', 'maybe', 'take', 'park', 'stupid', 'dog'}
{'him', 'so', 'dalmation', 'I', 'is', 'cute', 'love', 'my'}
{'posting', 'stop', 'stupid', 'worthless', 'garbage'}
{'licks', 'ate', 'steak', 'mr', 'to', 'how', 'stop', 'him', 'my'}
{'quit', 'worthless', 'buying', 'stupid', 'dog', 'food'}
{'ate', 'to', 'him', 'maybe', 'take', 'so', 'mr', 'posting', 'how', 'quit', 'worthless', 'has', 'help', 'buying', 'stupid', 'garbage', 'is', 'flea', 'cute', 'love', 'my', 'dog', 'food', 'not', 'stop', 'licks', 'steak', 'dalmation', 'park', 'I', 'please', 'problems'}


['ate',
 'to',
 'him',
 'maybe',
 'take',
 'so',
 'mr',
 'posting',
 'how',
 'quit',
 'worthless',
 'has',
 'help',
 'buying',
 'stupid',
 'garbage',
 'is',
 'flea',
 'cute',
 'love',
 'my',
 'dog',
 'food',
 'not',
 'stop',
 'licks',
 'steak',
 'dalmation',
 'park',
 'I',
 'please',
 'problems']

In [15]:
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList : 
            returnVec[vocabList.index(word)] = 1
        else : print ("the word: %s is not in my Vocabulary!" % word)
    return returnVec

In [16]:
setOfWords2Vec(myvocablist,postingList[1])

[0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0]

In [33]:
def trainNB0(trainMatrix, trainCategory) : 
    numTrainDocs = len(trainMatrix)
    numWords = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDocs)
    p0Num = np.ones(numWords) ; p1Num = np.ones(numWords)
    p0Denom = 2.0 ; p1Denom = 2.0
    for i in range(numTrainDocs) :
        if trainCategory[i] ==1 :
            p1Num += trainMatrix[i]
            p1Denom += sum(trainMatrix[i])
            print(p1Num)
            print(p1Denom)
        else : 
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = np.log(p1Num/p1Denom)
    p0Vect = np.log(p0Num/p0Denom)
    return p0Vect, p1Vect, pAbusive

In [12]:
listOPosts, listClasses = loadDataSet()

In [13]:
myVocabList = createVocabList(listOPosts)

{'please', 'has', 'help', 'problems', 'flea', 'my', 'dog'}
{'not', 'to', 'him', 'maybe', 'take', 'park', 'stupid', 'dog'}
{'him', 'so', 'dalmation', 'I', 'is', 'cute', 'love', 'my'}
{'posting', 'stop', 'stupid', 'worthless', 'garbage'}
{'licks', 'ate', 'steak', 'mr', 'to', 'how', 'stop', 'him', 'my'}
{'quit', 'worthless', 'buying', 'stupid', 'dog', 'food'}
{'ate', 'to', 'him', 'maybe', 'take', 'so', 'mr', 'posting', 'how', 'quit', 'worthless', 'has', 'help', 'buying', 'stupid', 'garbage', 'is', 'flea', 'cute', 'love', 'my', 'dog', 'food', 'not', 'stop', 'licks', 'steak', 'dalmation', 'park', 'I', 'please', 'problems'}


In [39]:
trainMat=[]
for postinDoc in listOPosts:
    trainMat.append(setOfWords2Vec(myVocabList, postinDoc))
trainMat

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1],
 [0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0],
 [0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [1,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]]

In [35]:
trainNB0(trainMat,listClasses)

[1. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 2. 1. 1. 1.]
10.0
[1. 2. 2. 2. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 2. 1. 2.
 2. 1. 1. 1. 2. 1. 1. 1.]
15.0
[1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 3. 1. 1. 2. 4. 2. 1. 1. 1. 1. 1. 3. 2. 2.
 2. 1. 1. 1. 2. 1. 1. 1.]
21.0


(array([-2.56494936, -2.56494936, -2.15948425, -3.25809654, -3.25809654,
        -2.56494936, -2.56494936, -3.25809654, -2.56494936, -3.25809654,
        -3.25809654, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
        -3.25809654, -2.56494936, -2.56494936, -2.56494936, -2.56494936,
        -1.87180218, -2.56494936, -3.25809654, -3.25809654, -2.56494936,
        -2.56494936, -2.56494936, -2.56494936, -3.25809654, -2.56494936,
        -2.56494936, -2.56494936]),
 array([-3.04452244, -2.35137526, -2.35137526, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -2.35137526, -3.04452244, -2.35137526,
        -1.94591015, -3.04452244, -3.04452244, -2.35137526, -1.65822808,
        -2.35137526, -3.04452244, -3.04452244, -3.04452244, -3.04452244,
        -3.04452244, -1.94591015, -2.35137526, -2.35137526, -2.35137526,
        -3.04452244, -3.04452244, -3.04452244, -2.35137526, -3.04452244,
        -3.04452244, -3.04452244]),
 0.5)

In [36]:
p0V,p1V,pAb=trainNB0(trainMat,listClasses)

[1. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 2.
 1. 1. 1. 1. 2. 1. 1. 1.]
10.0
[1. 2. 2. 2. 2. 1. 1. 2. 1. 1. 2. 1. 1. 1. 3. 2. 1. 1. 1. 1. 1. 2. 1. 2.
 2. 1. 1. 1. 2. 1. 1. 1.]
15.0
[1. 2. 2. 2. 2. 1. 1. 2. 1. 2. 3. 1. 1. 2. 4. 2. 1. 1. 1. 1. 1. 3. 2. 2.
 2. 1. 1. 1. 2. 1. 1. 1.]
21.0


In [40]:
p0V

array([-2.56494936, -2.56494936, -2.15948425, -3.25809654, -3.25809654,
       -2.56494936, -2.56494936, -3.25809654, -2.56494936, -3.25809654,
       -3.25809654, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
       -3.25809654, -2.56494936, -2.56494936, -2.56494936, -2.56494936,
       -1.87180218, -2.56494936, -3.25809654, -3.25809654, -2.56494936,
       -2.56494936, -2.56494936, -2.56494936, -3.25809654, -2.56494936,
       -2.56494936, -2.56494936])

In [41]:
len(p0V)

32

In [1]:
def classifyNB(vec2Classify, p0Vec, p1Vec, pClass1) :
    p1 = sum(vec2Classify*p1Vec) +log(pClass1)
    p0 = sum(vec2Classify * p0Vec) + log(1.0 - pClass1)
    if p1 > p0 :
        return 1
    else :
        return 0
    
def testingNB() : 
    listOPosts, listClasses = loadDataSet()
    myVocabList = createVocabList(listOPosts)
    trainMat = []
    for postinDoc in listOPosts :
        trainMat.append(setOfWords2Vec(myVocabList, postinDoc))
        p0V,p1V,pAb = trainNB0(array(trainMat), array(listClasses))
        testEntry = ['love','my','dalmation']
        thisDoc = array(setOfWords2Vec(myVocabList, testEntry))
        print (testEntry,'classified as : ', classifyNB(thisDoc,p0V,p1V,pAb))
        testEntry = ['stupid', 'garbage']
        thisDoc = array(setOfWords2Vec(myVocabList, testEntry))
        print(testEntry, 'classified as :', classifyNB(thisDoc,p0V,p1V,pAb))